//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface PagedResultOfAuditLog {
    items: AuditLog[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    totalPages: number;
}

export interface AuditLog {
    id: string;
    userId: string | undefined;
    user: User | undefined;
    eventType: AuditEventType;
    description: string;
    userAgent: string | undefined;
    timestamp: Date;
    success: boolean;
    errorMessage: string | undefined;
    preChangeValue: string | undefined;
    postChangeValue: string | undefined;
}

export interface IdentityUserOfGuid {
    id: string;
    userName: string | undefined;
    normalizedUserName: string | undefined;
    email: string | undefined;
    normalizedEmail: string | undefined;
    emailConfirmed: boolean;
    passwordHash: string | undefined;
    securityStamp: string | undefined;
    concurrencyStamp: string | undefined;
    phoneNumber: string | undefined;
    phoneNumberConfirmed: boolean;
    twoFactorEnabled: boolean;
    lockoutEnd: Date | undefined;
    lockoutEnabled: boolean;
    accessFailedCount: number;
}

export interface User extends IdentityUserOfGuid {
    firstName: string;
    lastName: string;
    email: string | undefined;
    status: UserStatus;
    lastLogin: Date | undefined;
    createdAt: Date;
    updatedAt: Date | undefined;
    avatar: string | undefined;
    permissions: Permission[];
    userRoles: UserRole[];
    permissionKeys: string[] | undefined;
}

export enum UserStatus {
    Active = "Active",
    Inactive = "Inactive",
    Pending = "Pending",
    Suspended = "Suspended",
}

export interface Permission {
    id: string;
    key: string;
    name: string;
    description: string;
    resource: string;
    action: string;
    category: string;
    isSystem: boolean;
    createdAt: Date;
}

export interface IdentityUserRoleOfGuid {
    userId: string;
    roleId: string;
}

export interface UserRole extends IdentityUserRoleOfGuid {
    user: User;
    role: Role;
}

export interface IdentityRoleOfGuid {
    id: string;
    name: string | undefined;
    normalizedName: string | undefined;
    concurrencyStamp: string | undefined;
}

export interface Role extends IdentityRoleOfGuid {
    name: string | undefined;
    description: string;
    permissions: Permission[];
    userRoles: UserRole[];
    isSystem: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export enum AuditEventType {
    Login = "Login",
    Logout = "Logout",
    TokenRefresh = "TokenRefresh",
    PasswordChange = "PasswordChange",
    PasswordReset = "PasswordReset",
    PasswordResetRequested = "PasswordResetRequested",
    PasswordResetCompleted = "PasswordResetCompleted",
    EmailConfirmed = "EmailConfirmed",
    EmailConfirmationResent = "EmailConfirmationResent",
    AccountLocked = "AccountLocked",
    AccountUnlocked = "AccountUnlocked",
    PermissionChanged = "PermissionChanged",
    RoleChanged = "RoleChanged",
    FailedLogin = "FailedLogin",
    TokenBlacklisted = "TokenBlacklisted",
    Created = "Created",
    Updated = "Updated",
    Deleted = "Deleted",
}

export interface Expression {
    nodeType: ExpressionType;
    type: string;
    canReduce: boolean;
}

export interface LambdaExpression extends Expression {
    type: string;
    typeCore: string;
    publicType: string;
    nodeType: ExpressionType;
    parameters: ParameterExpression[];
    name: string | undefined;
    nameCore: string | undefined;
    body: Expression;
    returnType: string;
    tailCall: boolean;
    tailCallCore: boolean;
    parameterCount: number;
}

export enum ExpressionType {
    Add = "Add",
    AddChecked = "AddChecked",
    And = "And",
    AndAlso = "AndAlso",
    ArrayLength = "ArrayLength",
    ArrayIndex = "ArrayIndex",
    Call = "Call",
    Coalesce = "Coalesce",
    Conditional = "Conditional",
    Constant = "Constant",
    Convert = "Convert",
    ConvertChecked = "ConvertChecked",
    Divide = "Divide",
    Equal = "Equal",
    ExclusiveOr = "ExclusiveOr",
    GreaterThan = "GreaterThan",
    GreaterThanOrEqual = "GreaterThanOrEqual",
    Invoke = "Invoke",
    Lambda = "Lambda",
    LeftShift = "LeftShift",
    LessThan = "LessThan",
    LessThanOrEqual = "LessThanOrEqual",
    ListInit = "ListInit",
    MemberAccess = "MemberAccess",
    MemberInit = "MemberInit",
    Modulo = "Modulo",
    Multiply = "Multiply",
    MultiplyChecked = "MultiplyChecked",
    Negate = "Negate",
    UnaryPlus = "UnaryPlus",
    NegateChecked = "NegateChecked",
    New = "New",
    NewArrayInit = "NewArrayInit",
    NewArrayBounds = "NewArrayBounds",
    Not = "Not",
    NotEqual = "NotEqual",
    Or = "Or",
    OrElse = "OrElse",
    Parameter = "Parameter",
    Power = "Power",
    Quote = "Quote",
    RightShift = "RightShift",
    Subtract = "Subtract",
    SubtractChecked = "SubtractChecked",
    TypeAs = "TypeAs",
    TypeIs = "TypeIs",
    Assign = "Assign",
    Block = "Block",
    DebugInfo = "DebugInfo",
    Decrement = "Decrement",
    Dynamic = "Dynamic",
    Default = "Default",
    Extension = "Extension",
    Goto = "Goto",
    Increment = "Increment",
    Index = "Index",
    Label = "Label",
    RuntimeVariables = "RuntimeVariables",
    Loop = "Loop",
    Switch = "Switch",
    Throw = "Throw",
    Try = "Try",
    Unbox = "Unbox",
    AddAssign = "AddAssign",
    AndAssign = "AndAssign",
    DivideAssign = "DivideAssign",
    ExclusiveOrAssign = "ExclusiveOrAssign",
    LeftShiftAssign = "LeftShiftAssign",
    ModuloAssign = "ModuloAssign",
    MultiplyAssign = "MultiplyAssign",
    OrAssign = "OrAssign",
    PowerAssign = "PowerAssign",
    RightShiftAssign = "RightShiftAssign",
    SubtractAssign = "SubtractAssign",
    AddAssignChecked = "AddAssignChecked",
    MultiplyAssignChecked = "MultiplyAssignChecked",
    SubtractAssignChecked = "SubtractAssignChecked",
    PreIncrementAssign = "PreIncrementAssign",
    PreDecrementAssign = "PreDecrementAssign",
    PostIncrementAssign = "PostIncrementAssign",
    PostDecrementAssign = "PostDecrementAssign",
    TypeEqual = "TypeEqual",
    OnesComplement = "OnesComplement",
    IsTrue = "IsTrue",
    IsFalse = "IsFalse",
}

export interface ParameterExpression extends Expression {
    type: string;
    nodeType: ExpressionType;
    name: string | undefined;
    isByRef: boolean;
}

export interface AuthResponse {
    user: UserResponse;
    token: string;
    expiresAt: Date;
}

export interface UserResponse {
    id: string;
    email: string | undefined;
    firstName: string;
    lastName: string;
    customPermissionsCount: number;
    isActive: boolean;
    userStatus: UserStatus;
    lastLogin: Date | undefined;
    createdAt: Date;
    updatedAt: Date | undefined;
    avatar: string | undefined;
    permissionKeys: string[] | undefined;
    role: RoleResponse | undefined;
    permissions: PermissionResponse[];
}

export interface RoleResponse {
    id: string;
    description: string;
    name: string;
    permissions: PermissionResponse[];
    users: UserResponse[];
    isSystem: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface PermissionResponse {
    id: string;
    key: string;
    name: string;
    description: string;
    resource: string;
    action: string;
    category: string;
    isSystem: boolean;
    createdAt: Date;
}

export interface LoginRequest {
    email: string;
    password: string;
}

export interface ForgotPasswordRequest {
    email: string;
}

export interface ResetPasswordRequest {
    email: string;
    token: string;
    newPassword: string;
}

export interface ChangePasswordRequest {
    currentPassword: string;
    newPassword: string;
    confirmPassword: string;
}

export interface ConfirmEmailRequest {
    email: string;
    token: string;
    password: string;
}

export interface PagedResultOfPermissionResponse {
    items: PermissionResponse[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    totalPages: number;
}

export interface PagedResultOfRoleResponse {
    items: RoleResponse[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    totalPages: number;
}

export interface ProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;

    [key: string]: any;
}

export interface HttpValidationProblemDetails extends ProblemDetails {
    errors: { [key: string]: string[]; };

    [key: string]: any;
}

export interface ValidationProblemDetails extends HttpValidationProblemDetails {
    errors: { [key: string]: string[]; };

    [key: string]: any;
}

export interface CreateRoleRequest {
    name: string;
    description: string;
    permissionKeys: string[];
}

export interface UpdateRoleRequest {
    name: string;
    description: string;
    permissionKeys: string[] | undefined;
}

export interface PagedResultOfUserResponse {
    items: UserResponse[];
    totalCount: number;
    pageNumber: number;
    pageSize: number;
    totalPages: number;
}

export interface CreateUserRequest {
    email: string;
    firstName: string;
    lastName: string;
    roleId: string;
    status: number;
}

export interface UpdateUserRequest {
    firstName: string;
    lastName: string;
    avatar: string | undefined;
    roleId: string | undefined;
    permissionKeys: string[] | undefined;
    status: number | undefined;
}

export interface ApproveUserRequest {
    roleId: string;
}