export const APP_PATHS = {
  HOME: "/",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  CONFIRM_EMAIL: "/confirm-email",
} as const;

export const AUTH_PATHS = {
  LOGIN: "/login",
  LOGOUT: "/logout",
  ME: "/me",
  REFRESH_TOKEN: "/refresh-token",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  CHANGE_PASSWORD: "/change-password",
  CONFIRM_EMAIL: "/confirm-email",
} as const;

export const BUTTON_LABELS = {
  EDIT: "Edit",
  DELETE: "Delete",
  SAVE: "Save",
  CANCEL: "Cancel",
  CONFIRM: "Confirm",
  CLOSE: "Close",
  SUBMIT: "Submit",
  SIGN_IN: "Sign in",
  SIGN_IN_WITH_GOOGLE: "Sign in with Google",
  REMEMBER_ME: "Remember me",
  OR_CONTINUE_WITH: "Or continue with",
  BACK_TO_USERS: "Back to Users",
  BACK_TO_ROLES: "Back to Roles",
} as const;

export const ERROR_MESSAGES = {
  NOT_FOUND: "Not found",
  LOADING_FAILED: "Failed to load data",
  GOOGLE_AUTH_FAILED: "Failed to authenticate with Google",
  WRONG_USERNAME_PASSWORD: "Incorrect username or password",
  SAVE_FAILED: "Failed to save changes",
  DELETE_FAILED: "Failed to delete item",
  NETWORK_ERROR: "Network error occurred",
  TOKEN_REFRESH_FAILED: "Token refresh failed",
  LOGIN_FAILED: "Login failed",
  INVALID_RESPONSE_DATA: "Invalid response data",
  FAILED_FETCH_DATA: "Failed to fetch data",
  FAILED_CREATE_DATA: "Failed to create",
  FAILED_UPDATE_DATA: "Failed to update",
  FAILED_DELETE_DATA: "Failed to delete",
  FAILED_APPROVE_DATA: "Failed to approve",
  FAILED_REJECT_DATA: "Failed to reject",
  VALIDATION_FAILED: "Validation failed",
  RATE_LIMIT_EXCEEDED: "Rate limit exceeded. Please try again later.",
  TOKEN_REVOKED: "Your session has expired. Please log in again.",
  SESSION_EXPIRED: "Your session has expired. Please log in again.",
} as const;

export const TEST_IDS = {
  LOGIN_FORM: "login-form",
  LOGIN_PAGE: "login-page",
  LOGIN_ERROR: "login-error",
  LOGIN_MESSAGE: "login-message",
  LOGIN_FORM_CONTAINER: "login-form-container",
  EMAIL_INPUT: "email-input",
  PASSWORD_INPUT: "password-input",
  PASSWORD_TOGGLE: "password-toggle",
  REMEMBER_ME: "remember-me",
  LOGIN_BUTTON: "login-button",
  LOADING_SPINNER: "loading-spinner",
  GOOGLE_LOGIN_BUTTON: "google-login-button",
  FORGOT_PASSWORD_LINK: "forgot-password-link",
  SIGN_UP_LINK: "sign-up-link",
  REMEMBER_ME_CHECKBOX: "remember-me-checkbox",
  LAYOUT_CONTAINER: "layout-container",
  MOBILE_SIDEBAR: "mobile-sidebar",
  MOBILE_SIDEBAR_CLOSE: "mobile-sidebar-close",
  MOBILE_NAVIGATION: "mobile-navigation",
  DESKTOP_SIDEBAR: "desktop-sidebar",
  DESKTOP_NAVIGATION: "desktop-navigation",
  MAIN_CONTENT: "main-content",
  TOP_BAR: "top-bar",
  MOBILE_MENU_BUTTON: "mobile-menu-button",
  MOBILE_MENU_TOGGLE: "mobile-menu-toggle",
  USER_MENU: "user-menu",
  USER_NAME: "user-name",
  USER_EMAIL: "user-email",
  LOGOUT_BUTTON: "logout-button",
  LOGOUT_LINK: "logout-link",
  PAGE_CONTENT: "space-y-6",
  FOOTER: "footer",
  SIDEBAR: "sidebar",
  NAV_ITEM: "nav-item",
  TABLE: "table",
  TABLE_EMPTY: "table-empty",
  TABLE_LOADING: "table-loading",
  TABLE_HEADER: "table-header",
  TABLE_ROW: "table-row",
  TABLE_SORTABLE: "table-sortable",
  TABLE_PAGINATION: "table-pagination",
  PAGINATION: "pagination",
  SEARCH_INPUT: "search-input",
  SEARCH_BUTTON: "search-button",
  CLEAR_SEARCH: "clear-search",
  STATUS_FILTER: "status-filter",
  SYSTEM_FILTER: "system-filter",
  SUBMIT_BUTTON: "submit-button",
  CANCEL_BUTTON: "cancel-button",
  CONFIRM_BUTTON: "confirm-button",
  CLOSE_MODAL: "close-modal",
  VIEW_DETAILS_BUTTON: "view-details-button",
  CONFIRM_DELETE_BUTTON: "confirm-delete-button",
  CANCEL_DELETE_BUTTON: "cancel-delete-button",
  BULK_ACTIONS: "bulk-actions",
  FORM_TITLE: "form-title",
  FIRST_NAME_INPUT: "first-name-input",
  LAST_NAME_INPUT: "last-name-input",
  ERROR_MESSAGE: "error-message",
  SUCCESS_MESSAGE: "success-message",
  WELCOME_MESSAGE: "welcome-message",
  ACCESS_DENIED: "access-denied",
  TOAST_CONTAINER: "toast-container",
  TOAST_SUCCESS: "toast-success",
  TOAST_ERROR: "toast-error",
  TOAST_INFO: "toast-info",
  TOAST_WARNING: "toast-warning",
  TOAST_TITLE: "toast-title",
  TOAST_MESSAGE: "toast-message",
  PAGE_TITLE: "page-title",
  MODAL: "modal",
  MODAL_TRIGGER: "modal-trigger",
  MODAL_CLOSE: "modal-close",
  CONFIRMATION_DIALOG: "confirmation-dialog",
  CONFIRMATION_MESSAGE: "confirmation-message",
  EXPORT_MODAL: "export-modal",
  EXPORT_MODAL_TITLE: "export-modal-title",
  CONFIRM_EXPORT_BUTTON: "confirm-export-button",
  USER_PROFILE_DROPDOWN: "user-profile-dropdown",
  PROFILE_MENU: "profile-menu",
  PROFILE_LINK: "profile-link",
  SETTINGS_LINK: "settings-link",
  USER_INFO: "user-info",
  THEME_TOGGLE: "theme-toggle",
  QUICK_ACTIONS: "quick-actions",
  ACTIVITY_ITEM: "activity-item",
  RECENT_ACTIVITY: "recent-activity",
  STATS_GRID: "stats-grid",
  STATS_CARDS: "stats-cards",
  BREADCRUMBS: "breadcrumbs",
  TABS: "tabs",
  CATEGORY_ITEM: "category-item",
  NO_USER: "no-user",
  MOCK_BUTTON: "mock-button",
  MOCK_CARD: "mock-card",
  MOCK_INPUT: "mock-input",
  MOCK_STATUS_BADGE: "mock-status-badge",
  MOCK_LOADING_SPINNER: "mock-loading-spinner",
  MOCK_MODAL: "mock-modal",
  MOCK_MODAL_PORTAL: "mock-modal-portal",
  MOCK_SEARCH_INPUT: "mock-search-input",
  MOCK_FILTER_SELECT: "mock-filter-select",
  MOCK_PERMISSION_SELECTOR: "mock-permission-selector",
  MOCK_STATS_CARD: "mock-stats-card",
  MOCK_DASHBOARD_CARD: "mock-dashboard-card",
  MOCK_BASE_TABLE_PAGE: "mock-base-table-page",
  MOCK_PAGINATION: "mock-pagination",
  MOCK_THEME_TOGGLE: "mock-theme-toggle",
  MOCK_BASE_PAGE: "mock-base-page",
  MOCK_ROLE_FILTERS: "mock-role-filters",
  MOCK_USER_GRID_PAGE: "mock-user-grid-page",
  MOCK_USER_DETAILS_PAGE: "mock-user-details-page",
  MOCK_PENDING_USERS_PAGE: "mock-pending-users-page",
  MOCK_USER_CREATE_PAGE: "mock-user-create-page",
  MOCK_USER_ROLE_PAGE: "mock-user-role-page",
  MOCK_USER_PERMISSION_PAGE: "mock-user-permission-page",
  MOCK_USER_FORM_MODAL: "mock-user-form-modal",
  MOCK_USER_ROLE_MODAL: "mock-user-role-modal",
  MOCK_USER_PERMISSION_MODAL: "mock-user-permission-modal",
  MOCK_HOME_PAGE: "mock-home-page",
  MOCK_PERMISSION_GUARD: "mock-permission-guard",
  MOCK_BASE_MODAL_PAGE: "mock-base-modal-page",
  MOCK_CUSTOM_HEADER: "mock-custom-header",
  MOCK_CUSTOM_FOOTER: "mock-custom-footer",
  MOCK_SUB_NAV: "mock-sub-nav",
  MOCK_CUSTOM_CONTENT: "mock-custom-content",
  COMPONENTS_REFERENCE_PAGE: "components-reference-page",
  COMPONENTS_TABS: "components-tabs",
  BUTTONS_SECTION: "buttons-section",
  BUTTON_PRIMARY: "button-primary",
  BUTTON_SECONDARY: "button-secondary",
  BUTTON_DANGER: "button-danger",
  BUTTON_SUCCESS: "button-success",
  BUTTON_SMALL: "button-small",
  BUTTON_MEDIUM: "button-medium",
  BUTTON_LARGE: "button-large",
  BUTTON_DISABLED: "button-disabled",
  BUTTON_WITH_ICON: "button-with-icon",
  FORMS_SECTION: "forms-section",
  INPUT_TEXT: "input-text",
  INPUT_EMAIL: "input-email",
  INPUT_PASSWORD: "input-password",
  SELECT_DROPDOWN: "select-dropdown",
  CHECKBOX: "checkbox",
  RADIO_BUTTON: "radio-button",
  TEXTAREA: "textarea",
  CARDS_SECTION: "cards-section",
  CARD_BASIC: "card-basic",
  CARD_WITH_HEADER: "card-with-header",
  CARD_WITH_FOOTER: "card-with-footer",
  MODALS_SECTION: "modals-section",
  TABLES_SECTION: "tables-section",
  NAVIGATION_SECTION: "navigation-section",
  FEEDBACK_SECTION: "feedback-section",
  PROGRESS_BAR: "progress-bar",
  PERMISSION_DEMO_SECTION: "permission-demo-section",
  PERMISSION_DEMO_TITLE: "permission-demo-title",
  THEME_SECTION: "theme-section",
  CODE_EXAMPLE: "code-example",
  COPY_CODE_BUTTON: "copy-code-button",
  COMPONENT_DESCRIPTION: "component-description",
  COMPONENT_PROPS: "component-props",
  COMPONENT_USAGE: "component-usage",
  DASHBOARD: "dashboard",
  ADMINISTRATOR_DASHBOARD: "administrator-dashboard",
  SUPPORT_DASHBOARD: "support-dashboard",
  REGULATOR_DASHBOARD: "regulator-dashboard",
  OPERATOR_DASHBOARD: "operator-dashboard",
  USER_PAGE: "user-page",
  USER_FORM: "user-form",
  USER_ROW: "user-row",
  PENDING_USERS_PAGE: "pending-users-page",
  PENDING_USER_CARD: "pending-user-card",
  EDIT_USER_BUTTON: "edit-user-button",
  DELETE_USER_BUTTON: "delete-user-button",
  MANAGE_ROLES_BUTTON: "manage-roles-button",
  MANAGE_PERMISSIONS_BUTTON: "manage-permissions-button",
  ROLE_PAGE: "role-page",
  ROLE_GRID_PAGE: "role-grid-page",
  ROLE_FORM: "role-form",
  ROLE_FORM_MODAL: "role-form-modal",
  ROLE_ROW: "role-row",
  ROLE_NAME: "role-name",
  ROLE_NAME_INPUT: "role-name-input",
  ROLE_DESCRIPTION: "role-description",
  ROLE_DETAILS: "role-details",
  ROLE_ACTIONS: "role-actions",
  ROLE_PERMISSIONS: "role-permissions",
  ROLE_STATS: "role-stats",
  ROLE_USERS: "role-users",
  ROLE_USER_COUNT: "role-user-count",
  ROLE_PERMISSION_COUNT: "role-permission-count",
  EDIT_ROLE_BUTTON: "edit-role-button",
  DELETE_ROLE_BUTTON: "delete-role-button",
  CANCEL_ROLE_BUTTON: "cancel-role-button",
  PERMISSION_PAGE: "permission-page",
  PERMISSION_GRID_PAGE: "permission-grid-page",
  PERMISSION_ROW: "permission-row",
  NAV_LOGIN: "nav-login",
} as const;
